# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Task config for So100 — auto-generated by create_task.py.

To customize further, edit this file directly after generation.
"""

import os

import isaaclab.envs.mdp as base_mdp
from isaaclab.assets import ArticulationCfg, AssetBaseCfg, RigidObjectCfg
from isaaclab.managers import EventTermCfg as EventTerm
from isaaclab.managers import ObservationGroupCfg as ObsGroup
from isaaclab.managers import ObservationTermCfg as ObsTerm
from isaaclab.managers import SceneEntityCfg
from isaaclab.managers import TerminationTermCfg as DoneTerm
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.sim.spawners.from_files.from_files_cfg import UsdFileCfg
from isaaclab.utils import configclass

from isaaclab_task_maker.assets import SCENES_DIR, OBJECTS_DIR, ROBOTS_DIR
from . import mdp
from isaaclab_task_maker.tasks.manager_based.base_il_env.base_il_env_cfg import BaseILEnvCfg

from isaaclab_assets.robots.so100 import LEROBOT_SO100_CFG  # isort: skip
from isaaclab.controllers.differential_ik_cfg import DifferentialIKControllerCfg
from isaaclab.envs.mdp.actions.actions_cfg import DifferentialInverseKinematicsActionCfg
from isaaclab.devices.device_base import DevicesCfg
from isaaclab.devices.keyboard import Se3KeyboardCfg

# =====================================================================
# Asset paths — loaded from assets/<category>/so100/
# =====================================================================
SCENE_USD_PATH = os.path.join(SCENES_DIR, "scene.usd")
TM7_BOWL_USD_PATH = os.path.join(OBJECTS_DIR, "tm7_bowl_collisions.usd")

# =====================================================================
# 1) SCENE
# =====================================================================
@configclass
class So100SceneCfg(InteractiveSceneCfg):
    """Scene configuration for So100."""

    scene: AssetBaseCfg = AssetBaseCfg(
        prim_path="{ENV_REGEX_NS}/Scene",
        spawn=UsdFileCfg(
            usd_path=SCENE_USD_PATH,
            scale=(1.0, 1.0, 1.0),
        ),
        init_state=AssetBaseCfg.InitialStateCfg(pos=(0.0, 0.0, 0.0), rot=(1.0, 0.0, 0.0, 0.0)),
    )

    robot: ArticulationCfg = LEROBOT_SO100_CFG.replace(
        prim_path="/World/envs/env_.*/Robot",
        init_state=ArticulationCfg.InitialStateCfg(
            pos=(0.0, 0.0, 0.0),
            rot=(1.0, 0.0, 0.0, 0.0),
            joint_pos={".*": 0.0},
            joint_vel={".*": 0.0},
        ),
    )

    tm7_bowl: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/Scene/tm7_bowl",
        spawn=UsdFileCfg(
            usd_path=TM7_BOWL_USD_PATH,
            scale=(1.0, 1.0, 1.0),
        ),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(0.5, 0.0, 0.1), rot=(1.0, 0.0, 0.0, 0.0)),
    )

# =====================================================================
# 2) ACTIONS
# =====================================================================
@configclass
class So100ActionsCfg:
    """Differential IK actions for So100."""

    arm_action = DifferentialInverseKinematicsActionCfg(
        asset_name="robot",
        joint_names=["shoulder_pan", "shoulder_lift", "elbow_flex", "wrist_flex", "wrist_roll"],
        body_name="jaw",
        controller=DifferentialIKControllerCfg(
            command_type="pose",
            use_relative_mode=False,
            ik_method="dls",
        ),
        body_offset=DifferentialInverseKinematicsActionCfg.OffsetCfg(pos=[0.0, 0.0, 0.0]),
    )

# =====================================================================
# 3) OBSERVATIONS
# =====================================================================
@configclass
class So100ObservationsCfg:
    """Observations for So100."""

    @configclass
    class PolicyCfg(ObsGroup):
        actions = ObsTerm(func=mdp.last_action)
        robot_joint_pos = ObsTerm(
            func=base_mdp.joint_pos,
            params={"asset_cfg": SceneEntityCfg("robot")},
        )

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = False

    policy: PolicyCfg = PolicyCfg()


# =====================================================================
# 4) EVENTS & TERMINATIONS
# =====================================================================
@configclass
class So100EventCfg:
    reset_all = EventTerm(func=mdp.reset_scene_to_default, mode="reset")


@configclass
class So100TerminationsCfg:
    time_out = DoneTerm(func=mdp.time_out, time_out=True)


# =====================================================================
# 5) FINAL CONFIG
# =====================================================================
@configclass
class So100TaskCfg(BaseILEnvCfg):

    scene: So100SceneCfg = So100SceneCfg(
        num_envs=1, env_spacing=2.5, replicate_physics=True
    )
    observations: So100ObservationsCfg = So100ObservationsCfg()
    actions: So100ActionsCfg = So100ActionsCfg()
    events: So100EventCfg = So100EventCfg()
    terminations: So100TerminationsCfg = So100TerminationsCfg()

    def __post_init__(self):
        super().__post_init__()

        # Teleop devices
        self.teleop_devices = DevicesCfg(
            devices={
                "keyboard": Se3KeyboardCfg(
                    pos_sensitivity=0.05,
                    rot_sensitivity=0.05,
                ),
            }
        )
