# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Task config for Tm7Gr1t — auto-generated by create_task.py.

To customize further, edit this file directly after generation.
"""

import os

import torch
from pink.tasks import FrameTask

import carb

import isaaclab.controllers.utils as ControllerUtils

import isaaclab.envs.mdp as base_mdp
from isaaclab.assets import ArticulationCfg, AssetBaseCfg, RigidObjectCfg
from isaaclab.managers import EventTermCfg as EventTerm
from isaaclab.managers import ObservationGroupCfg as ObsGroup
from isaaclab.managers import ObservationTermCfg as ObsTerm
from isaaclab.managers import SceneEntityCfg
from isaaclab.managers import TerminationTermCfg as DoneTerm
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.sim.spawners.from_files.from_files_cfg import UsdFileCfg
from isaaclab.utils import configclass

from isaaclab_task_maker.assets import SCENES_DIR, OBJECTS_DIR, ROBOTS_DIR
from . import mdp
from isaaclab_task_maker.tasks.manager_based.base_il_env.base_il_env_cfg import BaseILEnvCfg

from isaaclab_assets.robots.fourier import GR1T2_CFG  # isort: skip
from isaaclab.controllers.pink_ik import NullSpacePostureTask, PinkIKControllerCfg
from isaaclab.devices.device_base import DevicesCfg
from isaaclab.devices.openxr import OpenXRDeviceCfg, XrCfg
from isaaclab.envs.mdp.actions.pink_actions_cfg import PinkInverseKinematicsActionCfg
from isaaclab.devices.openxr.retargeters import GR1T2RetargeterCfg

# =====================================================================
# Asset paths — loaded from assets/<category>/tm7_gr1t/
# =====================================================================
SCENE_USD_PATH = os.path.join(SCENES_DIR, "tm7_gr1t", "scene.usd")
TM7_BOWL_USD_PATH = os.path.join(OBJECTS_DIR, "tm7_gr1t", "tm7_bowl_collisions.usd")
TM7_LID_USD_PATH = os.path.join(OBJECTS_DIR, "tm7_gr1t", "tm7_lid_collisions.usd")

# =====================================================================
# 1) SCENE
# =====================================================================
@configclass
class Tm7Gr1tSceneCfg(InteractiveSceneCfg):
    """Scene configuration for Tm7Gr1t."""

    scene: AssetBaseCfg = AssetBaseCfg(
        prim_path="{ENV_REGEX_NS}/Scene",
        spawn=UsdFileCfg(
            usd_path=SCENE_USD_PATH,
            scale=(1.0, 1.0, 1.0),
        ),
        init_state=AssetBaseCfg.InitialStateCfg(pos=(0.0, 0.0, 0.0), rot=(1.0, 0.0, 0.0, 0.0)),
    )

    robot: ArticulationCfg = GR1T2_CFG.replace(
        prim_path="/World/envs/env_.*/Robot",
        init_state=ArticulationCfg.InitialStateCfg(
            pos=(0.0, 0.9, 0.0),
            rot=(0.7071, 0.0, 0.0, -0.7071),
            joint_pos={".*": 0.0},
            joint_vel={".*": 0.0},
        ),
    )

    tm7_bowl: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/Scene/tm7_bowl",
        spawn=UsdFileCfg(
            usd_path=TM7_BOWL_USD_PATH,
            scale=(0.35, 0.35, 0.35),
        ),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(0.0, 0.5, 0.185), rot=(0.70711, 0.0, 0.0, 0.70711)),
    )

    tm7_lid: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/Scene/tm7_lid",
        spawn=UsdFileCfg(
            usd_path=TM7_LID_USD_PATH,
            scale=(0.35, 0.35, 0.35),
        ),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(0.0, 0.5, 0.2), rot=(0.5, 0.5, -0.5, 0.5)),
    )


# =====================================================================
# 2) ACTIONS
# =====================================================================
@configclass
class Tm7Gr1tActionsCfg:
    """Pink IK actions for Tm7Gr1t."""

    pink_ik_cfg = PinkInverseKinematicsActionCfg(
        pink_controlled_joint_names=["left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_pitch_joint", "left_wrist_yaw_joint", "left_wrist_roll_joint", "left_wrist_pitch_joint", "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_pitch_joint", "right_wrist_yaw_joint", "right_wrist_roll_joint", "right_wrist_pitch_joint"],
        hand_joint_names=["L_index_proximal_joint", "L_middle_proximal_joint", "L_pinky_proximal_joint", "L_ring_proximal_joint", "L_thumb_proximal_yaw_joint", "R_index_proximal_joint", "R_middle_proximal_joint", "R_pinky_proximal_joint", "R_ring_proximal_joint", "R_thumb_proximal_yaw_joint", "L_index_intermediate_joint", "L_middle_intermediate_joint", "L_pinky_intermediate_joint", "L_ring_intermediate_joint", "L_thumb_proximal_pitch_joint", "R_index_intermediate_joint", "R_middle_intermediate_joint", "R_pinky_intermediate_joint", "R_ring_intermediate_joint", "R_thumb_proximal_pitch_joint", "L_thumb_distal_joint", "R_thumb_distal_joint"],
        target_eef_link_names={"left_wrist": "left_hand_pitch_link", "right_wrist": "right_hand_pitch_link"},
        asset_name="robot",
        controller=PinkIKControllerCfg(
            articulation_name="robot",
            base_link_name="base_link",
            num_hand_joints=22,
            show_ik_warnings=False,
            fail_on_joint_limit_violation=False,
            variable_input_tasks=[
                FrameTask(
                    "GR1T2_fourier_hand_6dof_left_hand_pitch_link",
                    position_cost=8.0,
                    orientation_cost=2.0,
                    lm_damping=10,
                    gain=0.5,
                ),
                FrameTask(
                    "GR1T2_fourier_hand_6dof_right_hand_pitch_link",
                    position_cost=8.0,
                    orientation_cost=2.0,
                    lm_damping=10,
                    gain=0.5,
                ),
                NullSpacePostureTask(
                    cost=0.5,
                    lm_damping=1,
                    controlled_frames=[
                        "GR1T2_fourier_hand_6dof_left_hand_pitch_link", "GR1T2_fourier_hand_6dof_right_hand_pitch_link",
                    ],
                    controlled_joints=[
                        "left_shoulder_pitch_joint",
                        "left_shoulder_roll_joint",
                        "left_shoulder_yaw_joint",
                        "left_elbow_pitch_joint",
                        "right_shoulder_pitch_joint",
                        "right_shoulder_roll_joint",
                        "right_shoulder_yaw_joint",
                        "right_elbow_pitch_joint",
                        "waist_yaw_joint",
                        "waist_pitch_joint",
                        "waist_roll_joint",
                    ],
                    gain=0.3,
                ),
            ],
            fixed_input_tasks=[],
            xr_enabled=bool(carb.settings.get_settings().get("/app/xr/enabled")),
        ),
        enable_gravity_compensation=False,
    )

# =====================================================================
# 3) OBSERVATIONS
# =====================================================================
@configclass
class Tm7Gr1tObservationsCfg:
    """Observations for Tm7Gr1t."""

    @configclass
    class PolicyCfg(ObsGroup):
        actions = ObsTerm(func=mdp.last_action)
        robot_joint_pos = ObsTerm(
            func=base_mdp.joint_pos,
            params={"asset_cfg": SceneEntityCfg("robot")},
        )

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = False

    policy: PolicyCfg = PolicyCfg()


# =====================================================================
# 4) EVENTS & TERMINATIONS
# =====================================================================
@configclass
class Tm7Gr1tEventCfg:
    reset_all = EventTerm(func=mdp.reset_scene_to_default, mode="reset")


@configclass
class Tm7Gr1tTerminationsCfg:
    time_out = DoneTerm(func=mdp.time_out, time_out=True)


# =====================================================================
# 5) FINAL CONFIG
# =====================================================================
@configclass
class Tm7Gr1tTaskCfg(BaseILEnvCfg):

    scene: Tm7Gr1tSceneCfg = Tm7Gr1tSceneCfg(
        num_envs=1, env_spacing=2.5, replicate_physics=True
    )
    observations: Tm7Gr1tObservationsCfg = Tm7Gr1tObservationsCfg()
    actions: Tm7Gr1tActionsCfg = Tm7Gr1tActionsCfg()
    events: Tm7Gr1tEventCfg = Tm7Gr1tEventCfg()
    terminations: Tm7Gr1tTerminationsCfg = Tm7Gr1tTerminationsCfg()

    xr: XrCfg = XrCfg(
        anchor_pos=(0.0, 0.0, 0.0),
        anchor_rot=(1.0, 0.0, 0.0, 0.0),
    )

    NUM_OPENXR_HAND_JOINTS = 26

    def __post_init__(self):
        super().__post_init__()

        # Convert USD to URDF for Pink IK
        temp_urdf_output_path, temp_urdf_meshes_output_path = ControllerUtils.convert_usd_to_urdf(
            self.scene.robot.spawn.usd_path, self.temp_urdf_dir, force_conversion=True
        )
        self.actions.pink_ik_cfg.controller.urdf_path = temp_urdf_output_path
        self.actions.pink_ik_cfg.controller.mesh_path = temp_urdf_meshes_output_path

        # Teleop devices
        self.teleop_devices = DevicesCfg(
            devices={
                "handtracking": OpenXRDeviceCfg(
                    retargeters=[
                        GR1T2RetargeterCfg(
                            enable_visualization=True,
                            num_open_xr_hand_joints=2 * self.NUM_OPENXR_HAND_JOINTS,
                            sim_device=self.sim.device,
                            hand_joint_names=self.actions.pink_ik_cfg.hand_joint_names,
                        ),
                    ],
                    sim_device=self.sim.device,
                    xr_cfg=self.xr,
                ),
            },
        )

