# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Task config for LegoG1 — auto-generated by create_task.py.

To customize further, edit this file directly after generation.
"""

import os
import xml.etree.ElementTree as ET

import torch
from pink.tasks import FrameTask

import carb

import isaaclab.controllers.utils as ControllerUtils

import isaaclab.envs.mdp as base_mdp
import isaaclab.sim as sim_utils
from isaaclab.assets import ArticulationCfg, AssetBaseCfg, RigidObjectCfg
from isaaclab.managers import EventTermCfg as EventTerm
from isaaclab.managers import ObservationGroupCfg as ObsGroup
from isaaclab.managers import ObservationTermCfg as ObsTerm
from isaaclab.managers import SceneEntityCfg
from isaaclab.managers import TerminationTermCfg as DoneTerm
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.sensors import CameraCfg
from isaaclab.sim.spawners.from_files.from_files_cfg import UsdFileCfg
from isaaclab.utils import configclass

from lego_g1.assets import SCENES_DIR, OBJECTS_DIR, ROBOTS_DIR
from . import mdp
from lego_g1.base_il_env.base_il_env_cfg import BaseILEnvCfg

from isaaclab_assets.robots.unitree import G1_INSPIRE_FTP_CFG  # isort: skip
from isaaclab.controllers.pink_ik import NullSpacePostureTask, PinkIKControllerCfg
from isaaclab.devices.device_base import DevicesCfg
from isaaclab.devices.openxr import OpenXRDeviceCfg, XrCfg
from isaaclab.envs.mdp.actions.pink_actions_cfg import PinkInverseKinematicsActionCfg
from isaaclab.devices.openxr.retargeters.humanoid.unitree.inspire.g1_upper_body_retargeter import UnitreeG1RetargeterCfg

# =====================================================================
# Asset paths — loaded from assets/<category>/lego_g1/
# =====================================================================
SCENE_USD_PATH = os.path.join(SCENES_DIR, "lego.usd")
BRICK_2X2_USD_PATH = os.path.join(OBJECTS_DIR, "lego/brick_2x2_centered.usdc")

_HAND_CENTER_EEF_OFFSET = (0.05, 0.0, 0.0)
_LEFT_EEF_LINK = "left_hand_center_eef"
_RIGHT_EEF_LINK = "right_hand_center_eef"
_LEFT_EEF_URDF_FRAME = "g1_29dof_rev_1_0_left_hand_center_eef"
_RIGHT_EEF_URDF_FRAME = "g1_29dof_rev_1_0_right_hand_center_eef"
_LEFT_HAND_BASE_LINK = "L_hand_base_link"
_RIGHT_HAND_BASE_LINK = "R_hand_base_link"
_LEFT_WRIST_YAW_URDF_LINK = "g1_29dof_rev_1_0_left_wrist_yaw_link"
_RIGHT_WRIST_YAW_URDF_LINK = "g1_29dof_rev_1_0_right_wrist_yaw_link"
_LEFT_HAND_CENTER_USD_PARENT = f"/Robot/left_wrist_yaw_link/{_LEFT_HAND_BASE_LINK}"
_RIGHT_HAND_CENTER_USD_PARENT = f"/Robot/right_wrist_yaw_link/{_RIGHT_HAND_BASE_LINK}"

_PHYSICS_MATERIALS: dict[str, sim_utils.RigidBodyMaterialCfg] = {
    "brick_2x2": sim_utils.RigidBodyMaterialCfg(
        static_friction=1.2,
        dynamic_friction=1.0,
        restitution=0.0,
    ),
    "brick_2x2_1": sim_utils.RigidBodyMaterialCfg(
        static_friction=1.2,
        dynamic_friction=1.0,
        restitution=0.0,
    )
}

# Visual material overrides keyed by leaf prim name. Values are color slugs that
# match Looks/<color> under the referenced scene USD; the spawner resolves the
# full per-env path at runtime (e.g. /World/envs/env_0/Scene/Looks/green).
# stronger_than_descendants=True wins over any materials baked into the brick USD.
_VISUAL_MATERIAL_COLORS: dict[str, str] = {
    "brick_2x2": "blue",
    "brick_2x2_1": "red",
}


def _add_g1_hand_center_eefs_to_stage(robot_prim_path: str) -> None:
    """Add hand-center rigid-body EEFs to a spawned G1 robot prim."""
    from pxr import Gf, Sdf, UsdGeom, UsdPhysics

    stage = sim_utils.get_current_stage()

    for parent_suffix, eef_name in (
        (_LEFT_HAND_CENTER_USD_PARENT.removeprefix("/Robot"), _LEFT_EEF_LINK),
        (_RIGHT_HAND_CENTER_USD_PARENT.removeprefix("/Robot"), _RIGHT_EEF_LINK),
    ):
        parent_sdf_path = Sdf.Path(f"{robot_prim_path}{parent_suffix}")
        parent_prim = stage.GetPrimAtPath(parent_sdf_path)
        if not parent_prim.IsValid():
            raise RuntimeError(f"Cannot add '{eef_name}': USD parent prim does not exist at '{parent_sdf_path}'.")

        eef_path = parent_sdf_path.AppendChild(eef_name)
        eef_xform = UsdGeom.Xform.Define(stage, eef_path)
        eef_xform.SetResetXformStack(True)
        eef_xform.AddTranslateOp().Set(Gf.Vec3d(*_HAND_CENTER_EEF_OFFSET))

        eef_prim = eef_xform.GetPrim()
        rigid_body = UsdPhysics.RigidBodyAPI.Apply(eef_prim)
        rigid_body.CreateRigidBodyEnabledAttr(True)
        UsdPhysics.MassAPI.Apply(eef_prim).CreateMassAttr(0.001)

        joint = UsdPhysics.FixedJoint.Define(stage, parent_sdf_path.AppendChild(f"{eef_name}_fixed_joint"))
        joint.CreateBody0Rel().SetTargets([parent_sdf_path])
        joint.CreateBody1Rel().SetTargets([eef_path])
        joint.CreateLocalPos0Attr(Gf.Vec3f(*_HAND_CENTER_EEF_OFFSET))
        joint.CreateLocalPos1Attr(Gf.Vec3f(0.0, 0.0, 0.0))
        joint.CreateLocalRot0Attr(Gf.Quatf(1.0, Gf.Vec3f(0.0, 0.0, 0.0)))
        joint.CreateLocalRot1Attr(Gf.Quatf(1.0, Gf.Vec3f(0.0, 0.0, 0.0)))


def _find_urdf_link_name(root: ET.Element, suffix: str, fallback: str | None = None) -> str:
    for link in root.findall("link"):
        name = link.get("name")
        if name == suffix or (name is not None and name.endswith(f"_{suffix}")):
            return name
    if fallback is not None and root.find(f"./link[@name='{fallback}']") is not None:
        return fallback
    raise ValueError(f"Could not find URDF link ending in '{suffix}'.")


def _ensure_urdf_fixed_child_link(
    root: ET.Element,
    *,
    parent_link: str,
    child_link: str,
    joint_name: str,
    xyz: tuple[float, float, float],
) -> None:
    if root.find(f"./link[@name='{child_link}']") is None:
        ET.SubElement(root, "link", {"name": child_link})

    joint = root.find(f"./joint[@name='{joint_name}']")
    if joint is None:
        joint = ET.SubElement(root, "joint", {"name": joint_name, "type": "fixed"})
    else:
        joint.set("type", "fixed")

    for tag, link_name in (("parent", parent_link), ("child", child_link)):
        elem = joint.find(tag)
        if elem is None:
            elem = ET.SubElement(joint, tag)
        elem.set("link", link_name)

    origin = joint.find("origin")
    if origin is None:
        origin = ET.SubElement(joint, "origin")
    origin.set("xyz", f"{xyz[0]:g} {xyz[1]:g} {xyz[2]:g}")
    origin.set("rpy", "0 0 0")


def _patch_g1_hand_center_eefs_into_urdf(urdf_path: str) -> None:
    """Add the same fixed hand-center EEF links to Pink's generated URDF."""
    tree = ET.parse(urdf_path)
    root = tree.getroot()

    _ensure_urdf_fixed_child_link(
        root,
        parent_link=_find_urdf_link_name(root, _LEFT_HAND_BASE_LINK, fallback=_LEFT_WRIST_YAW_URDF_LINK),
        child_link=_LEFT_EEF_URDF_FRAME,
        joint_name=f"{_LEFT_EEF_URDF_FRAME}_fixed_joint",
        xyz=_HAND_CENTER_EEF_OFFSET,
    )
    _ensure_urdf_fixed_child_link(
        root,
        parent_link=_find_urdf_link_name(root, _RIGHT_HAND_BASE_LINK, fallback=_RIGHT_WRIST_YAW_URDF_LINK),
        child_link=_RIGHT_EEF_URDF_FRAME,
        joint_name=f"{_RIGHT_EEF_URDF_FRAME}_fixed_joint",
        xyz=_HAND_CENTER_EEF_OFFSET,
    )

    ET.indent(tree, space="  ")
    tree.write(urdf_path, encoding="utf-8", xml_declaration=True)


@sim_utils.clone
def spawn_g1_with_hand_center_eefs(
    prim_path: str,
    cfg: UsdFileCfg,
    translation: tuple[float, float, float] | None = None,
    orientation: tuple[float, float, float, float] | None = None,
    **kwargs,
):
    """Spawn the Unitree G1 USD and add task-specific hand-center EEF bodies."""
    prim = sim_utils.spawn_from_usd(prim_path, cfg, translation=translation, orientation=orientation, **kwargs)
    _add_g1_hand_center_eefs_to_stage(prim_path)
    return prim


@sim_utils.clone
def spawn_rigid_usd(
    prim_path: str,
    cfg: UsdFileCfg,
    translation: tuple[float, float, float] | None = None,
    orientation: tuple[float, float, float, float] | None = None,
    **kwargs,
):
    """Spawn a visual USD and explicitly apply rigid-body APIs to its root prim."""
    rigid_props = cfg.rigid_props or sim_utils.RigidBodyPropertiesCfg()
    mass_props = cfg.mass_props or sim_utils.MassPropertiesCfg(mass=0.05)
    collision_props = cfg.collision_props or sim_utils.CollisionPropertiesCfg()
    mesh_collision_props = sim_utils.SDFMeshPropertiesCfg()

    cfg.rigid_props = None
    cfg.mass_props = None
    cfg.collision_props = None
    try:
        prim = sim_utils.spawn_from_usd(prim_path, cfg, translation=translation, orientation=orientation, **kwargs)
    finally:
        cfg.rigid_props = rigid_props
        cfg.mass_props = mass_props
        cfg.collision_props = collision_props

    sim_utils.define_rigid_body_properties(prim_path, rigid_props)
    sim_utils.define_mass_properties(prim_path, mass_props)
    sim_utils.define_collision_properties(prim_path, collision_props)
    sim_utils.define_mesh_collision_properties(prim_path, mesh_collision_props)

    leaf = prim_path.rstrip("/").rsplit("/", 1)[-1]
    mat_cfg = _PHYSICS_MATERIALS.get(leaf)
    if mat_cfg is not None:
        mat_path = f"{prim_path}/physicsMaterial"
        mat_cfg.func(mat_path, mat_cfg)
        sim_utils.bind_physics_material(prim_path, mat_path)

    color = _VISUAL_MATERIAL_COLORS.get(leaf)
    if color is not None:
        env_ns = prim_path.rstrip("/").rsplit("/", 1)[0]
        sim_utils.bind_visual_material(prim_path, f"{env_ns}/Scene/Looks/{color}")
    return prim

def attach_cameras(scene_cfg) -> None:
    """Attach the head + wrist cameras to a LegoG1 scene cfg.

    Kept as a module-level helper so the teleop launcher can re-attach them after
    IsaacLab's XR pipeline strips CameraCfg attributes via remove_camera_configs.
    """
    scene_cfg.head_camera = CameraCfg(
        prim_path="{ENV_REGEX_NS}/Robot/torso_link/d435_link/head_camera",
        update_period=0.0,
        height=480,
        width=640,
        data_types=["rgb"],
        spawn=sim_utils.PinholeCameraCfg(
            focal_length=12.0,
            focus_distance=400.0,
            horizontal_aperture=20.955,
            clipping_range=(0.05, 10.0),
        ),
        offset=CameraCfg.OffsetCfg(
            pos=(0.0, 0.0, 0.0),
            rot=(0.5, 0.5, -0.5, -0.5),
            convention="opengl",
        ),
    )
    scene_cfg.right_wrist_camera = CameraCfg(
        prim_path="{ENV_REGEX_NS}/Robot/right_wrist_yaw_link/right_wrist_camera",
        update_period=0.0,
        height=480,
        width=640,
        data_types=["rgb"],
        spawn=sim_utils.PinholeCameraCfg(
            focal_length=10.0,
            focus_distance=400.0,
            horizontal_aperture=20.955,
            clipping_range=(0.05, 10.0),
        ),
        offset=CameraCfg.OffsetCfg(
            pos=(0.01, 0.05, 0.12),
            rot=(0.65326, 0.27061, -0.27059, -0.6533),
            convention="opengl",
        ),
    )
    scene_cfg.left_wrist_camera = CameraCfg(
        prim_path="{ENV_REGEX_NS}/Robot/left_wrist_yaw_link/left_wrist_camera",
        update_period=0.0,
        height=480,
        width=640,
        data_types=["rgb"],
        spawn=sim_utils.PinholeCameraCfg(
            focal_length=10.0,
            focus_distance=400.0,
            horizontal_aperture=20.955,
            clipping_range=(0.05, 10.0),
        ),
        offset=CameraCfg.OffsetCfg(
            pos=(0.01, -0.05, 0.12),
            rot=(0.65328, 0.2706, -0.2706, -0.65328),
            convention="opengl",
        ),
    )


# =====================================================================
# 1) SCENE
# =====================================================================
@configclass
class LegoG1SceneCfg(InteractiveSceneCfg):
    """Scene configuration for LegoG1."""

    scene: AssetBaseCfg = AssetBaseCfg(
        prim_path="{ENV_REGEX_NS}/Scene",
        spawn=UsdFileCfg(
            usd_path=SCENE_USD_PATH,
            scale=(1.0, 1.0, 1.0),
        ),
        init_state=AssetBaseCfg.InitialStateCfg(pos=(0.0, 0.0, 0.0), rot=(1.0, 0.0, 0.0, 0.0)),
    )

    dome_light: AssetBaseCfg = AssetBaseCfg(
        prim_path="/World/DomeLight",
        spawn=sim_utils.DomeLightCfg(
            intensity=1500.0,
            color=(1.0, 1.0, 1.0),
        ),
    )

    robot: ArticulationCfg = G1_INSPIRE_FTP_CFG.replace(
        prim_path="/World/envs/env_.*/Robot",
        init_state=ArticulationCfg.InitialStateCfg(
            pos=(-1.05, 0.0, 0.8),
            rot=(1.0, 0.0, 0.0, 0.0),
            joint_pos={".*": 0.0},
            joint_vel={".*": 0.0},
        ),
    )

    brick_2x2: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/brick_2x2",
        spawn=UsdFileCfg(
            func=spawn_rigid_usd,
            usd_path=BRICK_2X2_USD_PATH,
            scale=(0.3, 0.3, 0.3),
            rigid_props=sim_utils.RigidBodyPropertiesCfg(),
            mass_props=sim_utils.MassPropertiesCfg(mass=0.05),
            collision_props=sim_utils.CollisionPropertiesCfg(),
        ),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(-0.7, -0.2, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )

    brick_2x2_1: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/brick_2x2_1",
        spawn=UsdFileCfg(
            func=spawn_rigid_usd,
            usd_path=BRICK_2X2_USD_PATH,
            scale=(0.3, 0.3, 0.3),
            rigid_props=sim_utils.RigidBodyPropertiesCfg(),
            mass_props=sim_utils.MassPropertiesCfg(mass=0.05),
            collision_props=sim_utils.CollisionPropertiesCfg(),
        ),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(-0.7, 0.2, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )

# =====================================================================
# 2) ACTIONS
# =====================================================================
@configclass
class LegoG1ActionsCfg:
    """Pink IK actions for LegoG1."""

    pink_ik_cfg = PinkInverseKinematicsActionCfg(
        pink_controlled_joint_names=[".*_shoulder_pitch_joint", ".*_shoulder_roll_joint", ".*_shoulder_yaw_joint", ".*_elbow_joint", ".*_wrist_yaw_joint", ".*_wrist_roll_joint", ".*_wrist_pitch_joint"],
        hand_joint_names=["L_index_proximal_joint", "L_middle_proximal_joint", "L_pinky_proximal_joint", "L_ring_proximal_joint", "L_thumb_proximal_yaw_joint", "R_index_proximal_joint", "R_middle_proximal_joint", "R_pinky_proximal_joint", "R_ring_proximal_joint", "R_thumb_proximal_yaw_joint", "L_index_intermediate_joint", "L_middle_intermediate_joint", "L_pinky_intermediate_joint", "L_ring_intermediate_joint", "L_thumb_proximal_pitch_joint", "R_index_intermediate_joint", "R_middle_intermediate_joint", "R_pinky_intermediate_joint", "R_ring_intermediate_joint", "R_thumb_proximal_pitch_joint", "L_thumb_intermediate_joint", "R_thumb_intermediate_joint", "L_thumb_distal_joint", "R_thumb_distal_joint"],
        target_eef_link_names={"left_wrist": _LEFT_EEF_LINK, "right_wrist": _RIGHT_EEF_LINK},
        asset_name="robot",
        controller=PinkIKControllerCfg(
            articulation_name="robot",
            base_link_name="pelvis",
            num_hand_joints=24,
            show_ik_warnings=False,
            fail_on_joint_limit_violation=False,
            variable_input_tasks=[
                FrameTask(
                    _LEFT_EEF_URDF_FRAME,
                    position_cost=8.0,
                    orientation_cost=2.0,
                    lm_damping=10,
                    gain=0.5,
                ),
                FrameTask(
                    _RIGHT_EEF_URDF_FRAME,
                    position_cost=8.0,
                    orientation_cost=2.0,
                    lm_damping=10,
                    gain=0.5,
                ),
                NullSpacePostureTask(
                    cost=0.5,
                    lm_damping=1,
                    controlled_frames=[
                        _LEFT_EEF_URDF_FRAME,
                        _RIGHT_EEF_URDF_FRAME,
                    ],
                    controlled_joints=[
                        "waist_yaw_joint",
                        "waist_pitch_joint",
                        "waist_roll_joint",
                    ],
                    gain=0.3,
                ),
            ],
            fixed_input_tasks=[],
            xr_enabled=bool(carb.settings.get_settings().get("/app/xr/enabled")),
        ),
        enable_gravity_compensation=False,
    )

# =====================================================================
# 3) OBSERVATIONS
# =====================================================================
# ── Subtask termination-signal parameters ──────────────────────────────────
# These dummy values are referenced from the SubtaskTermsCfg terms below.
# Tune them after recording a few demonstrations and inspecting the logged
# EEF / object trajectories.
#
# Object → arm assignment follows the initial scene layout:
#   brick_2x2   is at y = -0.2  → assigned to the RIGHT arm
#   brick_2x2_1 is at y = +0.2  → assigned to the LEFT  arm
_LEFT_BRICK = "brick_2x2_1"
_RIGHT_BRICK = "brick_2x2"
# Inspire-hand proximal joints; mean joint angle is used as a coarse
# "closed-ness" proxy. Only the thumb, index, and middle fingers are
# included — the thumb uses its pitch (curl-down) joint as the closest
# analog to the other fingers' proximal flexion.
_LEFT_GRIPPER_JOINTS = r"L_(index_proximal_joint|middle_proximal_joint|thumb_proximal_pitch_joint)"
_RIGHT_GRIPPER_JOINTS = r"R_(index_proximal_joint|middle_proximal_joint|thumb_proximal_pitch_joint)"

# Dummy thresholds — replace with values derived from real demos.
_DIST_TO_BRICK_THRESHOLD = 0.2            # m  (eef ↔ brick)
_BRICK_TO_TARGET_THRESHOLD = 0.29          # m  (brick ↔ placement target)
_GRIPPER_CLOSED_THRESHOLD = 0.5            # rad  (proximal joint mean)
_GRIPPER_OPEN_THRESHOLD = 0.15              # rad  (proximal joint mean)

# Per-arm placement targets and idle poses, in env-local frame.
_LEFT_TARGET_POS = (-0.4, 0.05, 0.83)
_RIGHT_TARGET_POS = (-0.4, -0.05, 0.83)
_LEFT_IDLE_POS = (-0.3, 0.3, 1.2)
_RIGHT_IDLE_POS = (-0.3, -0.3, 1.2)
_IDLE_BOX_HALF_EXTENT = (0.1, 0.1, 0.1)   # m  (idle pose tolerance)


@configclass
class LegoG1ObservationsCfg:
    """Observations for LegoG1."""

    @configclass
    class PolicyCfg(ObsGroup):
        actions = ObsTerm(func=mdp.last_action)
        robot_joint_pos = ObsTerm(
            func=base_mdp.joint_pos,
            params={"asset_cfg": SceneEntityCfg("robot")},
        )
        # End-effector pose observations.
        # Names MUST be `{eef_name}_eef_pos` / `{eef_name}_eef_quat` — `BaseILEnv.get_robot_eef_pose`
        # reads these out of obs_buf by that exact key when the Mimic recorder asks for EEF poses.
        left_eef_pos = ObsTerm(func=mdp.get_eef_pos, params={"link_name": _LEFT_EEF_LINK})
        left_eef_quat = ObsTerm(func=mdp.get_eef_quat, params={"link_name": _LEFT_EEF_LINK})
        right_eef_pos = ObsTerm(func=mdp.get_eef_pos, params={"link_name": _RIGHT_EEF_LINK})
        right_eef_quat = ObsTerm(func=mdp.get_eef_quat, params={"link_name": _RIGHT_EEF_LINK})

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = False

    @configclass
    class SubtaskTermsCfg(ObsGroup):
        """Subtask termination signals consumed by the annotated-teleop recorder.

        Each term returns a ``(num_envs, 1)`` binary float tensor that is ``1`` when
        the corresponding subtask is complete. ``BaseILEnv.get_subtask_term_predicates``
        reads this group out of ``obs_buf["subtask_terms"]`` and feeds it to the
        recorder's dwell-and-latch logic. The attribute names below must match the
        ``subtask_term_signal`` values declared in ``lego_g1_mimic_cfg.py``.
        """

        # ── LEFT arm subtasks ─────────────────────────────────────────────
        grasp_brick_left = ObsTerm(
            func=mdp.grasp_brick_done,
            params={
                "signal_name": "grasp_brick_left",
                "eef_link": _LEFT_EEF_LINK,
                "object_name": _LEFT_BRICK,
                "dist_threshold": _DIST_TO_BRICK_THRESHOLD,
                "gripper_joint_pattern": _LEFT_GRIPPER_JOINTS,
                "gripper_closed_threshold": _GRIPPER_CLOSED_THRESHOLD,
            },
        )
        move_brick_left = ObsTerm(
            func=mdp.move_brick_done,
            params={
                "signal_name": "move_brick_left",
                "eef_link": _LEFT_EEF_LINK,
                "object_name": _LEFT_BRICK,
                "target_pos": _LEFT_TARGET_POS,
                "eef_dist_threshold": _DIST_TO_BRICK_THRESHOLD,
                "target_dist_threshold": _BRICK_TO_TARGET_THRESHOLD,
                "gripper_joint_pattern": _LEFT_GRIPPER_JOINTS,
                "gripper_closed_threshold": _GRIPPER_CLOSED_THRESHOLD,
            },
        )
        release_brick_left = ObsTerm(
            func=mdp.release_brick_done,
            params={
                "signal_name": "release_brick_left",
                "object_name": _LEFT_BRICK,
                "target_pos": _LEFT_TARGET_POS,
                "target_dist_threshold": _BRICK_TO_TARGET_THRESHOLD,
                "gripper_joint_pattern": _LEFT_GRIPPER_JOINTS,
                "gripper_open_threshold": _GRIPPER_OPEN_THRESHOLD,
            },
        )
        idle_left = ObsTerm(
            func=mdp.idle_done,
            params={
                "signal_name": "idle_left",
                "eef_link": _LEFT_EEF_LINK,
                "idle_pos": _LEFT_IDLE_POS,
                "threshold": _IDLE_BOX_HALF_EXTENT,
            },
        )

        # ── RIGHT arm subtasks ────────────────────────────────────────────
        grasp_brick_right = ObsTerm(
            func=mdp.grasp_brick_done,
            params={
                "signal_name": "grasp_brick_right",
                "eef_link": _RIGHT_EEF_LINK,
                "object_name": _RIGHT_BRICK,
                "dist_threshold": _DIST_TO_BRICK_THRESHOLD,
                "gripper_joint_pattern": _RIGHT_GRIPPER_JOINTS,
                "gripper_closed_threshold": _GRIPPER_CLOSED_THRESHOLD,
            },
        )
        move_brick_right = ObsTerm(
            func=mdp.move_brick_done,
            params={
                "signal_name": "move_brick_right",
                "eef_link": _RIGHT_EEF_LINK,
                "object_name": _RIGHT_BRICK,
                "target_pos": _RIGHT_TARGET_POS,
                "eef_dist_threshold": _DIST_TO_BRICK_THRESHOLD,
                "target_dist_threshold": _BRICK_TO_TARGET_THRESHOLD,
                "gripper_joint_pattern": _RIGHT_GRIPPER_JOINTS,
                "gripper_closed_threshold": _GRIPPER_CLOSED_THRESHOLD,
            },
        )
        release_brick_right = ObsTerm(
            func=mdp.release_brick_done,
            params={
                "signal_name": "release_brick_right",
                "object_name": _RIGHT_BRICK,
                "target_pos": _RIGHT_TARGET_POS,
                "target_dist_threshold": _BRICK_TO_TARGET_THRESHOLD,
                "gripper_joint_pattern": _RIGHT_GRIPPER_JOINTS,
                "gripper_open_threshold": _GRIPPER_OPEN_THRESHOLD,
            },
        )
        idle_right = ObsTerm(
            func=mdp.idle_done,
            params={
                "signal_name": "idle_right",
                "eef_link": _RIGHT_EEF_LINK,
                "idle_pos": _RIGHT_IDLE_POS,
                "threshold": _IDLE_BOX_HALF_EXTENT,
            },
        )

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = False

    policy: PolicyCfg = PolicyCfg()
    subtask_terms: SubtaskTermsCfg = SubtaskTermsCfg()


# =====================================================================
# 4) EVENTS & TERMINATIONS
# =====================================================================
@configclass
class LegoG1EventCfg:
    reset_all = EventTerm(func=mdp.reset_scene_to_default, mode="reset")


@configclass
class LegoG1TerminationsCfg:
    time_out = DoneTerm(func=mdp.time_out, time_out=True)


# =====================================================================
# 5) FINAL CONFIG
# =====================================================================
@configclass
class LegoG1TaskCfg(BaseILEnvCfg):

    scene: LegoG1SceneCfg = LegoG1SceneCfg(
        num_envs=1, env_spacing=2.5, replicate_physics=True
    )
    observations: LegoG1ObservationsCfg = LegoG1ObservationsCfg()
    actions: LegoG1ActionsCfg = LegoG1ActionsCfg()
    events: LegoG1EventCfg = LegoG1EventCfg()
    terminations: LegoG1TerminationsCfg = LegoG1TerminationsCfg()

    xr: XrCfg = XrCfg(
        anchor_pos=(-1.05, 0.0, -0.3),
        anchor_rot=(1.0, 0.0, 0.0, 0.0),
    )

    NUM_OPENXR_HAND_JOINTS = 26

    def __post_init__(self):
        # EEF list — picked up by BaseILEnv methods and wired into the
        # recorder's entity_order by BaseILEnvCfg.__post_init__. Set before
        # super() so the base post-init sees it.
        self.eef_names = ["left", "right"]

        # Pink IK action tensor layout (per `_extract_controlled_frame_poses`):
        #   [L_pos(3), L_quat(4), R_pos(3), R_quat(4), hand_joints(num_hand_joints)]
        # Frame-task order follows `variable_input_tasks` in the controller cfg,
        # which here is left, then right.
        self.eef_action_slices = {
            "left":  {"pos": (0, 3),  "quat": (3, 7)},
            "right": {"pos": (7, 10), "quat": (10, 14)},
        }

        # Per-arm finger-joint column indices. Inspire hand interleaves L/R in
        # `hand_joint_names`, so the gripper slice for each arm is a *list of
        # indices* rather than a contiguous range. Derive it from the actual
        # joint name order so reordering the YAML stays correct.
        _pose_offset = 14  # 2 frame tasks * (3 + 4)
        _hand_names = self.actions.pink_ik_cfg.hand_joint_names
        self.eef_gripper_slices = {
            "left":  [_pose_offset + i for i, n in enumerate(_hand_names) if n.startswith("L_")],
            "right": [_pose_offset + i for i, n in enumerate(_hand_names) if n.startswith("R_")],
        }

        super().__post_init__()

        # Episode duration in seconds. Combined with `terminations.time_out`,
        # this causes ManagerBasedRLEnv to reset the env once this many seconds
        # of sim time have elapsed.
        self.episode_length_s = 30.0

        # Cameras — attached to robot links. Note: when running under XR teleop,
        # IsaacLab's `remove_camera_configs` strips these before scene build; the
        # bundled teleop script re-adds them via `attach_cameras` below.
        attach_cameras(self.scene)

        # Add hand-center EEF bodies in the spawned USD stage, then mirror them
        # into the generated URDF so observations and Pink IK use the same frames.
        self.scene.robot.spawn.func = spawn_g1_with_hand_center_eefs

        # Convert the original Unitree USD to URDF for Pink IK. The task-local
        # EEF links are patched into the URDF after conversion.
        temp_urdf_output_path, temp_urdf_meshes_output_path = ControllerUtils.convert_usd_to_urdf(
            self.scene.robot.spawn.usd_path, self.temp_urdf_dir, force_conversion=True
        )
        _patch_g1_hand_center_eefs_into_urdf(temp_urdf_output_path)
        self.actions.pink_ik_cfg.controller.urdf_path = temp_urdf_output_path
        self.actions.pink_ik_cfg.controller.mesh_path = temp_urdf_meshes_output_path

        # Teleop devices
        self.teleop_devices = DevicesCfg(
            devices={
                "handtracking": OpenXRDeviceCfg(
                    retargeters=[
                        UnitreeG1RetargeterCfg(
                            enable_visualization=True,
                            num_open_xr_hand_joints=2 * self.NUM_OPENXR_HAND_JOINTS,
                            sim_device=self.sim.device,
                            hand_joint_names=self.actions.pink_ik_cfg.hand_joint_names,
                        ),
                    ],
                    sim_device=self.sim.device,
                    xr_cfg=self.xr,
                ),
            }
        )
